# Generated by Django 5.0.3 on 2024-03-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraworkinfo',
            old_name='resume',
            new_name='work',
        ),
    ]
