# Generated by Django 5.0.3 on 2024-03-07 14:55

import customers.validation
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_account_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_course_lvl', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('user_variant', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(35)])),
                ('user_faculty', models.CharField(blank=True, choices=[('IKTA', 'Faculty of IKTA'), ('IKHI', 'Faculty of IKHI'), ('IAДУ', 'Faculty of IAДУ'), ('IАРД', 'Faculty of IАРД'), ('ІБІС', 'Faculty of ІБІС'), ('ІГДГ', 'Faculty of ІГДГ'), ('ІГСН', 'Faculty of ІГСН'), ('ІНЕМ', 'Faculty of ІНЕМ'), ('IЕСК', 'Faculty of ІЕСК'), ('ІППТ', 'Faculty of ІППТ'), ('ІППО', 'Faculty of ІППО'), ('ІМФН', 'Faculty of ІМФН'), ('ІСТР', 'Faculty of ІСТР'), ('ІТРЕ', 'Faculty of ІТРЕ'), ('IXXT', 'Faculty of IXXT'), ('IAДУ', 'Faculty of IXXT')], max_length=4, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(error_messages={'unique': "You've already registered"}, max_length=254, unique=True, validators=[customers.validation.CustomEmailValidator(allowlist=('lpnu.ua',), code=None, message='Incorrect email, check if it ends with: lpnu.ua, other university')]),
        ),
        migrations.AddField(
            model_name='account',
            name='user_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.userinfo'),
        ),
    ]
