# Generated by Django 5.0.3 on 2024-03-07 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_userinfo_alter_account_email_account_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_info',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.userinfo'),
        ),
    ]
