# Generated by Django 5.0.3 on 2024-03-09 22:20

import customers.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(error_messages={'unique': "You've already registered"}, max_length=254, unique=True, validators=[customers.validation.CustomEmailValidator(allowlist=('lpnu.ua',), code=None, message='Incorrect email, check if it ends with: lpnu.ua, other university')]),
        ),
    ]
