# Generated by Django 5.0.3 on 2024-03-13 22:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraResumeInfo',
            fields=[
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users_resume.resume')),
                ('resume_course_lvl', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
            ],
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='extraInfo',
            new_name='description',
        ),
    ]
