# Generated by Django 5.0.3 on 2024-03-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_resume', '0003_alter_extraresumeinfo_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraresumeinfo',
            old_name='resume',
            new_name='resumeID',
        ),
    ]
